port:  5000
markdown: kramdown
name: Derek Eder
title: Derek Eder
url: https://derekeder.com
encoding: utf-8
timezone: America/Chicago
description: "Partner at DataMade, Co-found of Open City, and leader of the Chi Hack Night. I make stuff with open data."
permalink: /:categories/:title
navigation:
- text: <i class='fa fa-fw fa-home'></i>
  url: /index.html
- text: Talks
  url: /talks/index.html
- text: Projects
  url: /projects/index.html
- text: Blog
  url: /blog/index.html
- text: About
  url: /about/index.html
plugins:
  - jekyll-redirect-from