port:  5000
markdown: kramdown
name: Derek Eder
title: Derek Eder
url: https://derekeder.com
encoding: utf-8
timezone: America/Chicago
description: "I'm an entrepreneur, developer and one of the leaders of the civic technology community in Chicago."
permalink: /:categories/:title
navigation:
- text: <i class='fa fa-fw fa-home'></i>
  url: /index.html
- text: Talks
  url: /talks/index.html
- text: Maps
  url: /maps/index.html
- text: Projects
  url: /projects/index.html
- text: Blog
  url: /blog/index.html
- text: About
  url: /about/index.html
gems:
  - jekyll-redirect-from